server:
  port: 8084
spring:
  application:
    name: matching-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: matching-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer


location:
  service:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health, info